---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver(httpd) on redhat7
    yum:
     name: "{{webserveronredhat}}"
     state: present
    when: ansible_os_family== "RedHat"

  - name: start the service
    service:
     name: "{{webserveronredhat}}"
     state: started
    when: ansible_os_family== "RedHat" 
